[package]
name = "beagle_avmu"
version = "0.1.0"
authors = ["jnowaczek <jnowaczek@users.noreply.github.com>"]

[dependencies]
ws = "*"
crossbeam = "*"
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.39"